### ISSUE TITLE
配置文件有问题 

### ISSUE THREAD

**Issue by Jack1c** [kaito-kidd/markdown-image-alfred#5]
Starting debug for 'Markdown image'

[2017-05-13 20:35:43][ERROR: action.script] Traceback (most recent call last):
  File "processer.py", line 13, in <module>
    from config import (
  File "/Users/jack4c/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.61C335B3-5B13-4949-8BC5-3F62221BED8E/config.py", line 13
    BUCKET_NAME = ‘image’
                  ^
SyntaxError: invalid syntax
[2017-05-13 20:36:50][ERROR: action.script] Traceback (most recent call last):
  File "processer.py", line 13, in <module>
    from config import (
  File "/Users/jack4c/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.61C335B3-5B13-4949-8BC5-3F62221BED8E/config.py", line 13
    BUCKET_NAME = ‘image’
                  ^

BUCKET_NAME 的分号有问题

修改后的 : 

# coding: utf8

"""
请在下面填入正确的七牛配置
"""

# Access key/Secret key
# 参见：七牛 - 个人中心 - 秘钥管理
ACCESS_KEY = ''
SECRET_KEY = ''

# 七牛空间名,即建立存储空间时填写的名字
BUCKET_NAME = ''

# 图床域名
# 参见：七牛 - 内容管理 - 外链域名
URI_PREFIX = 'opw58jxdy.bkt.clouddn.com'

**Comment by kaito-kidd** [comment]
配置文件打开后，引号有可能会变成中文引号，可先手动修改修复。后续使用其他配置文件避免此问题。

**Comment by pengpn** [comment]
17-09-10 23:40:30][ERROR: action.script] Traceback (most recent call last):
  File "processer.py", line 156, in <module>
    main()
  File "processer.py", line 153, in main
    process()
  File "processer.py", line 60, in process
    width, height = _get_img_size(img_path)
  File "processer.py", line 95, in _get_img_size
    % img_path).read()
UnicodeEncodeError: 'ascii' codec can't encode characters in position 41-44: ordinal not in range(128)


这个编码问题怎么处理 我不会python呢
